# Generated by Django 5.0.7 on 2024-08-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='sold',
            field=models.IntegerField(max_length=1000),
        ),
    ]
