# Generated by Django 5.0.7 on 2024-08-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('Records', 'Disques'), ('Clothing', 'Vêtements'), ('Posters', 'Affiches'), ('Miscellaneous', 'Divers')], default='disques', max_length=30),
            preserve_default=False,
        ),
    ]
